services:
  - type: web
    name: crondash
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: alerts@crondash.com
